name:                chords
version:             0.0.1.0
github:              "moritzploss/chords"
license:             BSD3
author:              "Moritz Ploss"
maintainer:          "example@example.com"
copyright:           "2020 Moritz Ploss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/moritzploss/chords#readme>

dependencies:
- base >= 4.7 && < 5
- hspec == 2.7.*
- containers == 0.6.*
- pcre-heavy
- pcre-light
- bytestring

library:
  source-dirs: src

executables:
  chords-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chords

tests:
  chords-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chords
